# Use an official openjdk runtime as the base image
FROM openjdk:11-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the host to the container
COPY ../target/recipegenie-0.0.1-SNAPSHOT.jar /app/

# Expose the port that the application runs on
EXPOSE 8080

# Start the application
CMD ["java", "-jar", "your-application-name.jar"]
